FROM openjdk:8-jdk-alpine
MAINTAINER baeldung.com
WORKDIR C:\Users\goutam.sarkar\Desktop\important_docs\Training\Docker
COPY demo-0.0.1-SNAPSHOT.jar demo-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/demo-0.0.1-SNAPSHOT.jar"]